// <auto-generated />
using System;
using Chronos.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chronos.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(ChronosDbContext))]
    [Migration("20260826230624_InicialChronos")]
    partial class InicialChronos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chronos.Domain.Entidades.Checada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_utc");

                    b.Property<Guid?>("AjustadaPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ajustada_por_usuario_id");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<DateOnly>("DiaLaboral")
                        .HasColumnType("date")
                        .HasColumnName("dia_laboral");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("HuellaDispositivo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("huella_dispositivo");

                    b.Property<DateTimeOffset>("MomentoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("momento_utc");

                    b.Property<string>("MotivoAjuste")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_ajuste");

                    b.Property<int>("NivelConfianza")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_confianza");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("PuntajeConfianza")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_confianza");

                    b.Property<Guid?>("SedeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sede_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_checadas");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_checadas_estado")
                        .HasFilter("estado = 2");

                    b.HasIndex("MomentoUtc")
                        .HasDatabaseName("ix_checadas_momento_utc");

                    b.HasIndex("SedeId")
                        .HasDatabaseName("ix_checadas_sede_id");

                    b.HasIndex("EmpleadoId", "DiaLaboral")
                        .HasDatabaseName("ix_checadas_empleado_id_dia_laboral");

                    b.ToTable("checadas", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.CredencialWebAuthn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("aa_guid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset?>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_utc");

                    b.Property<byte[]>("ClavePublica")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("clave_publica");

                    b.Property<long>("ContadorFirmas")
                        .HasColumnType("bigint")
                        .HasColumnName("contador_firmas");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<byte[]>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreAmigable")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_amigable");

                    b.Property<string>("TipoDispositivo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo_dispositivo");

                    b.Property<DateTimeOffset?>("UltimoUsoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso_utc");

                    b.HasKey("Id")
                        .HasName("pk_credenciales_web_authn");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("ix_credenciales_web_authn_credential_id");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("ix_credenciales_web_authn_empleado_id");

                    b.ToTable("credenciales_web_authn", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset?>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_utc");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sede_id");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.HasIndex("SedeId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_departamentos_sede_id_codigo");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset?>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_utc");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("CorreoCorporativo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correo_corporativo");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_empleado");

                    b.Property<string>("Puesto")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("puesto");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sede_id");

                    b.Property<Guid?>("TurnoId")
                        .HasColumnType("uuid")
                        .HasColumnName("turno_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_empleados");

                    b.HasIndex("CorreoCorporativo")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_correo_corporativo");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("ix_empleados_departamento_id");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_numero_empleado");

                    b.HasIndex("SedeId")
                        .HasDatabaseName("ix_empleados_sede_id");

                    b.HasIndex("TurnoId")
                        .HasDatabaseName("ix_empleados_turno_id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_usuario_id")
                        .HasFilter("usuario_id IS NOT NULL");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset?>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_utc");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<string>("Direccion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id")
                        .HasName("pk_sedes");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_sedes_codigo");

                    b.ToTable("sedes", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.SenalPresencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_utc");

                    b.Property<DateTimeOffset>("CapturadaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturada_utc");

                    b.Property<Guid>("ChecadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("checada_id");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_json");

                    b.Property<int>("PesoAplicado")
                        .HasColumnType("integer")
                        .HasColumnName("peso_aplicado");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_senales_presencia");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_senales_presencia_tipo");

                    b.HasIndex("ChecadaId", "Tipo")
                        .HasDatabaseName("ix_senales_presencia_checada_id_tipo");

                    b.ToTable("senales_presencia", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset?>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_utc");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<int>("DiasLaborales")
                        .HasColumnType("integer")
                        .HasColumnName("dias_laborales");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_entrada");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_salida");

                    b.Property<int>("MinutosDescanso")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_descanso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("ToleranciaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tolerancia_minutos");

                    b.HasKey("Id")
                        .HasName("pk_turnos");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_turnos_nombre");

                    b.ToTable("turnos", (string)null);
                });

            modelBuilder.Entity("Chronos.Infrastructure.Identidad.RolAplicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Chronos.Infrastructure.Identidad.UsuarioAplicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NombreParaMostrar")
                        .HasColumnType("text")
                        .HasColumnName("nombre_para_mostrar");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset?>("UltimoAccesoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_utc");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Checada", b =>
                {
                    b.HasOne("Chronos.Domain.Entidades.Empleado", "Empleado")
                        .WithMany("Checadas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checadas_empleados_empleado_id");

                    b.HasOne("Chronos.Domain.Entidades.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_checadas_sedes_sede_id");

                    b.Navigation("Empleado");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.CredencialWebAuthn", b =>
                {
                    b.HasOne("Chronos.Domain.Entidades.Empleado", "Empleado")
                        .WithMany("Credenciales")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credenciales_web_authn_empleados_empleado_id");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Departamento", b =>
                {
                    b.HasOne("Chronos.Domain.Entidades.Sede", "Sede")
                        .WithMany("Departamentos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departamentos_sedes_sede_id");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Empleado", b =>
                {
                    b.HasOne("Chronos.Domain.Entidades.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_departamentos_departamento_id");

                    b.HasOne("Chronos.Domain.Entidades.Sede", "Sede")
                        .WithMany("Empleados")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_sedes_sede_id");

                    b.HasOne("Chronos.Domain.Entidades.Turno", "Turno")
                        .WithMany("Empleados")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_empleados_turnos_turno_id");

                    b.Navigation("Departamento");

                    b.Navigation("Sede");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Sede", b =>
                {
                    b.OwnsOne("Chronos.Domain.ValueObjects.Geocerca", "Geocerca", b1 =>
                        {
                            b1.Property<Guid>("SedeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitud")
                                .HasColumnType("double precision")
                                .HasColumnName("geocerca_latitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("double precision")
                                .HasColumnName("geocerca_longitud");

                            b1.Property<int>("RadioMetros")
                                .HasColumnType("integer")
                                .HasColumnName("geocerca_radio_metros");

                            b1.HasKey("SedeId");

                            b1.ToTable("sedes");

                            b1.WithOwner()
                                .HasForeignKey("SedeId")
                                .HasConstraintName("fk_sedes_sedes_id");
                        });

                    b.Navigation("Geocerca");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.SenalPresencia", b =>
                {
                    b.HasOne("Chronos.Domain.Entidades.Checada", "Checada")
                        .WithMany("Senales")
                        .HasForeignKey("ChecadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_senales_presencia_checadas_checada_id");

                    b.Navigation("Checada");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Infrastructure.Identidad.RolAplicacion", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Infrastructure.Identidad.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Infrastructure.Identidad.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Infrastructure.Identidad.RolAplicacion", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Chronos.Infrastructure.Identidad.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Infrastructure.Identidad.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Checada", b =>
                {
                    b.Navigation("Senales");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Empleado", b =>
                {
                    b.Navigation("Checadas");

                    b.Navigation("Credenciales");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Sede", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Chronos.Domain.Entidades.Turno", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
